stages:
  - build

ubuntu-16.04:
  variables:
    QCOW2_IMAGE: 'https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img'
  stage: build
  script:
    - vagrant-build
  tags:
    - vagrant
  except:
    - tags

ubuntu-18.04:
  variables:
    QCOW2_IMAGE: 'https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img'
  stage: build
  script:
    - vagrant-build
  tags:
    - vagrant
  except:
    - tags

debian-9.11:
  variables:
    QCOW2_IMAGE: 'https://cdimage.debian.org/cdimage/openstack/archive/9.11.2-20190926/debian-9.11.2-20190926-openstack-amd64.qcow2'
  stage: build
  script:
    - vagrant-build
  tags:
    - vagrant
  except:
    - tags

centos-7:
  variables:
    QCOW2_IMAGE: 'https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1907.qcow2'
  stage: build
  script:
    - vagrant-build
  tags:
    - vagrant
  except:
    - tags

openSUSE-Leap-15.1:
  variables:
    QCOW2_IMAGE: 'https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.1/images/openSUSE-Leap-15.1-OpenStack.x86_64.qcow2'
  stage: build
  script:
    - vagrant-build
  tags:
    - vagrant
  except:
    - tags

release-ubuntu-16.04:
  variables:
    QCOW2_IMAGE: 'https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img'
  stage: build
  script:
    - vagrant-build
  artifacts:
    paths:
      - 'build/*'
  tags:
    - vagrant
  only:
    - tags

release-ubuntu-18.04:
  variables:
    QCOW2_IMAGE: 'https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img'
  stage: build
  script:
    - vagrant-build
  artifacts:
    paths:
      - 'build/*'
  tags:
    - vagrant
  only:
    - tags

release-debian-9.11:
  variables:
    QCOW2_IMAGE: 'https://cdimage.debian.org/cdimage/openstack/archive/9.11.2-20190926/debian-9.11.2-20190926-openstack-amd64.qcow2'
  stage: build
  script:
    - vagrant-build
  artifacts:
    paths:
      - 'build/*'
  tags:
    - vagrant
  only:
    - tags

release-centos-7:
  variables:
    QCOW2_IMAGE: 'https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1907.qcow2'
  stage: build
  script:
    - vagrant-build
  artifacts:
    paths:
      - 'build/*'
  tags:
    - vagrant
  only:
    - tags

release-openSUSE-Leap-15.1:
  variables:
    QCOW2_IMAGE: 'https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.1/images/openSUSE-Leap-15.1-OpenStack.x86_64.qcow2'
  stage: build
  script:
    - vagrant-build
  artifacts:
    paths:
      - 'build/*'
  tags:
    - vagrant
  only:
    - tags
